apiVersion: apps/v1 
kind: Deployment
metadata:
  name: virtualtechbox-regapp
  labels: 
     app: aviapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: aviapp

  template:
    metadata:
      labels:
        app: aviapp
    spec:
      containers:
      - name: aviapp
        image: avinashbudhya/aviapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
