apiVersion: v1
kind: Service
metadata:
  name: virtualtechbox-service
  labels:
    app: aviapp 
spec:
  selector:
    app: aviapp 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
